name: Pre-release VS Code Extension

on:
  push:
    branches: [ main ]

jobs:
  pre-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate pre-release version
      id: version
      run: |
        # Get current version from package.json (e.g., "1.0.0")
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        # Generate pre-release version with timestamp (e.g., "1.0.20250718202055")
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        # Extract major.minor from current version and append timestamp
        MAJOR_MINOR=$(echo $CURRENT_VERSION | cut -d. -f1,2)
        PRE_RELEASE_VERSION="${MAJOR_MINOR}.${TIMESTAMP}"
        echo "version=$PRE_RELEASE_VERSION" >> $GITHUB_OUTPUT
        echo "Pre-release version: $PRE_RELEASE_VERSION"
        
    - name: Update package.json with pre-release version
      run: |
        npm version ${{ steps.version.outputs.version }} --no-git-tag-version
        
    - name: Package extension
      run: npm run package
      
    - name: Publish pre-release to marketplace
      run: npm run publish -- --pre-release
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
        
    - name: Upload VSIX artifact
      uses: actions/upload-artifact@v4
      with:
        name: vsix-pre-release
        path: "*.vsix"
        retention-days: 30